language: python

python:
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

before_install:
    - pip --quiet install coverage

install:
    - python setup.py --quiet install

script:
    - python test_eradicate.py
    - coverage run test_eradicate.py
    - coverage report --show-missing
