language: python

python:
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - pip --quiet install coverage

install:
    - python setup.py --quiet install

script:
    - python test_eradicate.py

after_success:
    - coverage run --include='eradicate.py,test_eradicate.py' test_eradicate.py
    - coverage report --show-missing

    - pip install --quiet coveralls
    - coveralls
